font_family Iosevka
bold_font auto
italic_font no
bold_italic_font auto
enable_audio_bell no
font_size 19.3
window_padding_width 8
cursor_trail 1
confirm_os_window_close 0
disable_ligatures always
hide_window_decorations titlebar-only

mouse_hide_wait -3.0
tab_bar_style powerline
tab_powerline_style round

include guttenbergovitz.conf
# include colors.conf
# include compline.conf
# include jelly.conf

term xterm-256color
background_opacity 0.8
background_blur 40
